Issue165
oss-slu/DroneWorld pull request #169
Opened 2024-11-11 20:40 UTC by Damerson1

Fixes #165 

The local file saving for png and html files was removed and replaced with the new GCS file saving. The reports are all uploaded to the gcs through the ThreeDimensionalGrapher.
 
-Much of the local file saving was removed in order to make way for saving files to the GCS. 
-Two functions were added to choose between uploading html files and uploading Png files. 
-Each function used to create the graphs are no longer static. This change was needed in order to allow self-calls, no issues has been shown as a result. 
- GCS uploading was added to each Draw function. 
 
This was needed because uploading files directly to GCS improves accessibility and streamlines the storage process by eliminating the need for local file storage.

Issue165 still has a problem with uploading the files to the correct files paths and with uploading files with duplicate names that are already located in the cloud. Otherwise, the files will upload to the GCS, assuming there's no duplicate names, trying to delete and overwrite an existing file that was previously uploaded.

2024-11-11 23:28 UTC, Hoshi-Okami reviewed
All of the files from the Acceptance Reports seem to be going into the GCS bucket, but the file paths aren't matching the previous ones. You may have to go back to working with the time stamps to fix this issue.

2024-11-12 18:03 UTC, mohamdlog requested changes
The updated `ThreeDimensionalGrapher` class has an issue with file paths not matching the intended structure, causing uploads to incorrect locations.

2024-11-12 18:03 UTC, 9LogM commented on backend/PythonClient/multirotor/util/graph/three_dimensional_grapher.py
> +            self._upload_plot(full_target_directory ,fig)
You are passing the arguments to `_upload_plot` in the wrong order. You pass `full_target_directory` first and `fig` second, whereas `_upload_plot` expects `fig` first and `file_name` second.

2024-11-12 18:03 UTC, 9LogM commented on backend/PythonClient/multirotor/util/graph/three_dimensional_grapher.py
> +            full_target_directory = os.path.join(self.log_subdir, self.__class__.__name__, file_name)
This conflicts with how `GCSStorageService` handles the upload path.

2024-11-18 17:12 UTC, closed without merging