166 add functionality to upload log text report files to google drive
oss-slu/DroneWorld pull request #170
Opened 2024-11-11 21:30 UTC by nguzinski

#166 
allows for automatic uploading of log files to Google Drive

this was added incase Google Cloud is unwanted/unavailable/ to allow for easier use of other storage devices

Built out from the previously created abstract storage service class, locks the thread during upload, creates the text file, the meta data for the upload, and uploads using the key.json.
Further, there is built-in testing if the gd_storage_service.py is ran as main.

2024-11-12 05:28 UTC, Damerson1 reviewed
The code runs as expected. The test also shows if the file is uploaded or not. You may consider checking if the folder_id actually exists before attempting to use it. Example: If folder_id do this else create folder_id. It's just a small check in case the folder doesn't exist, the code will have a way to verify that's the case or possible handle it. Otherwise, the code runs as expected.

2024-11-12 19:08 UTC, mohamdlog requested changes
I had to modify a few things to get the project running (see my reviews). Uploading worked afterward. However, your code does not use real folders. Instead, it employs a pseudo-hierarchy:

![Screenshot 2024-11-12 130301](https://github.com/user-attachments/assets/fc41729c-065b-4b69-a615-912e7a5dcf88)

Google Drive, unlike Google Cloud Storage, does support creating actual folders.

2024-11-12 19:08 UTC, 9LogM commented on .gitignore
> +backend/key.json
You don’t need to add this to prevent pushing the `key.json` file, as it was already included in the `.gitignore` on the line above.

2024-11-12 19:08 UTC, 9LogM commented on backend/PythonClient/multirotor/storage/gd_storage_service.py
> +from abstract.storage_service import StorageServiceInterface
If you want to use relative imports, you just need to use a single period `(.)`, which refers to the current package.

2024-11-12 19:08 UTC, mohamdlog commented on backend/PythonClient/multirotor/storage/gd_storage_service.py
> +            'backend/key.json', scopes=SCOPES)
The previous implementation was already trying to find `key.json` in the `backend` directory. Your implementation  causes an error: `FileNotFoundError: [Errno 2] No such file or directory: 'backend/key.json'`.

2024-11-19 19:44 UTC, mohamdlog reviewed
Your code still does not use real folders. Instead, it employs a pseudo-hierarchy:
![Screenshot 2024-11-19 134243](https://github.com/user-attachments/assets/7d5e51ac-fc21-400e-b737-13c608dc3303)

2024-11-19 19:57 UTC, merged