Made working product of fuzzy testing checkboxes
oss-slu/DroneWorld pull request #31
Opened 2023-10-14 01:10 UTC by sr259

Made it so that three checkboxes show up after the fuzzy tester is clicked. It is implemented so that there always needs to be one enabled.

2023-10-22 16:58 UTC, yashaswini-slu requested changes
Don’t enable the options by default, user should enable it
<img width="1436" alt="Screenshot 2023-10-22 at 11 56 49" src="https://github.com/oss-slu/DroneWorld/assets/113057349/cdfb3887-5afd-47cf-963c-68ee9a5794f7">

2023-10-22 17:11 UTC, sr259 commented
Hi @yashaswini-slu, i believe the current implementation works best. The way it is implemented has it so you cant have them all checked off, since having them checked off means you don't want anything fuzzy tested, which would get rid of the point of enabling the fuzzy test to begin with. I think having the user unclick the desired boxes they don't want fuzzy tested works best.

2023-10-22 19:43 UTC, yashaswini-slu approved these changes

2023-10-24 00:53 UTC, kate-holdener commented
@yashaswini-slu you approved this PR, but there is a merge conflict with main. Make sure to resolve the conflict before merging.

2023-10-24 23:06 UTC, merged