Add not found page
oss-slu/DroneWorld pull request #95
Opened 2024-05-25 12:58 UTC by Alhajideen

In this milestone, I have added the folllowing;
- Add a not-found page for wrong urls
Purpose
- This proactive approach takes users to a customized page, maintaining app structure instead of the default react 404 page

![Uploading Screenshot 2024-05-25 at 1.55.44 PM.png…]()

2024-05-28 18:43 UTC, kungfuchicken commented
It looks like there is not an open issue on this that you're resolving. I'm just confirming, this is just a general improvement you're suggesting?

2024-05-28 18:46 UTC, Alhajideen commented
Positive. There is no open issue for this. I am suggesting a general improvement.

2024-09-14 21:16 UTC, mohamdlog requested changes
**Requests:**
- Please change message to: "The page you are trying to open does not exist. You may have mistyped the address, or the page may have been moved to a different URL. If you believe this is an error, please contact support."
- The font differences between the files are due to different styling methods. Please ensure the font on this page matches the others for consistency.

Otherwise, looks good.

2024-09-29 06:26 UTC, mohamdlog approved these changes
Looks good, great work.

2024-09-29 06:26 UTC, mohamdlog commented on frontend/src/App.js
> +import './styles.css';
Good for consistency

2024-09-29 06:26 UTC, mohamdlog commented on frontend/src/App.js
> +          <Route exact path='/about-us' element={<AboutUs />} />
This is good practice

2024-09-29 06:30 UTC, merged